import type { CustomDraft, Inputs } from '../types';
import { createCustomLoadId } from './persistence';

export const defaultInputs: Inputs = {
    distanceM: 100,
    temperatureC: 15,
    pressureHpa: 1013.25,
    pressureSource: 'stationPressure',
    pressureAltitudeM: 0,
    geometricAltitudeM: 0,
    altimeterSettingHpa: 1013.25,
    humidityPercent: 50,
    headwindMps: 0,
    crosswindMps: 0,
    altitudeDependentAtmosphere: false,
    useLocalGravity: false,
    coriolisEnabled: false,
    latitudeDeg: 45,
    azimuthDeg: 0,
    targetInclinationDeg: 0,
    targetElevationM: 0,
    windLayers: [],
    windProvenance: '',
    vitalZoneM: 0.15,
    shotgunSightM: 0.025,
    rifleSightM: 0.04,
    shotgunZeroM: 50,
    rifleZeroM: 100,
    shotgunMvMultiplier: 1,
    rifleMvMultiplier: 1,
    rifleTwistInches: 10,
    twistDirection: 1,
    shotgunTemperatureVelocityProfile: [],
    rifleTemperatureVelocityProfile: [],
    shotgunTemperatureVelocitySource: '',
    rifleTemperatureVelocitySource: '',
    buckshotPattern: {
        enabled: false,
        loadId: 'builtin:winchester-00-buck',
        choke: 'cylinder',
        deformationClass: 'unknown',
        pelletVelocityStandardDeviationMps: 0,
        targetRangeM: 25,
        minimumPelletCount: 1,
        target: {
            shape: 'circle',
            widthM: 0.3,
            heightM: 0.3,
            centerHorizontalM: 0,
            centerVerticalM: 0,
        },
        observations: [],
    },
};

export function createDefaultCustomDraft(): CustomDraft {
    return {
        id: createCustomLoadId(),
        name: 'Custom load',
        drag: 'G1',
        group: 'rifle',
        massG: 10.886,
        mv: 823,
        bc: 0.475,
        bcMode: 'constant',
        bcBands: [
            { minimumVelocityMps: 0, ballisticCoefficient: 0.4 },
            { minimumVelocityMps: 400, ballisticCoefficient: 0.45 },
            { minimumVelocityMps: 700, ballisticCoefficient: 0.475 },
        ],
        machCdDiameterMm: 7.82,
        machCdPoints: [
            { mach: 0, dragCoefficient: 0.24 },
            { mach: 0.8, dragCoefficient: 0.25 },
            { mach: 1, dragCoefficient: 0.42 },
            { mach: 1.2, dragCoefficient: 0.36 },
            { mach: 2, dragCoefficient: 0.27 },
            { mach: 3, dragCoefficient: 0.22 },
        ],
        dragDataMetadata: {
            citation: 'User-entered data',
            sourceUrl: '',
            license: 'Unspecified',
            sourceChecksumSha256: '',
            domainMinimum: null,
            domainMaximum: null,
        },
        sphereMm: 8.382,
        density: 11340,
        count: 1,
        length: 0,
        diameter: 0.308,
        twist: 0,
    };
}
